config/routes.rb
Rails.application.routes.draw do
  resources :conversations

  root to: 'conversations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages

  validates :name, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages

  attr_accessor :content

  before_save :process_content, if: :has_content?

  def self.with_messages
    includes(messages: [:channel, :participant])
  end

  def has_content?
    content.present?
  end

  private

  def process_content
    result = chat_parser.parse(content)

    self.note = note.to_s + result.note
    messages << result.messages
    self.content = nil
  end

  def chat_parser
    @_chat_parser ||= ChatParser::Parser.new(ChatParser::Formats::GENERIC)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation, touch: true
  belongs_to :channel, touch: true
  belongs_to :participant, touch: true

  validates :participant, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :messages

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = Conversation.all
  end

  def show
    @conversation = Conversation.with_messages.find(params[:id])
  end

  def new
    @conversation = Conversation.new
  end

  def create
    @conversation = Conversation.new(conversation_params)

    if @conversation.save
      redirect_to conversation_path(@conversation),
                  notice: "Successfully created a new conversation"
    else
      render action: :new
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:title, :note, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.slim
h1 Conversations

ul.conversations
  - @conversations.each do |conversation|
    li
      h4
        = link_to conversation.title, conversation_path(conversation)
        - if conversation.occured_on.present?
          span.occured_on= " on #{conversation.occured_on}"
      - if conversation.note.present?
        p= conversation.note

= link_to 'Add Conversation', new_conversation_path, class: 'pure-button pure-button-primary'

app/views/conversations/new.html.slim
h1 Add conversation

= form_for @conversation, html: { class: "pure-form pure-form-aligned" } do |f|
  .pure-control-group
    = f.label :title
    = f.text_field :title, class: "pure-u-3-4"

  .pure-control-group
    = f.label :note
    = f.text_area :note, class: "pure-u-3-4"

  .pure-control-group
    = f.label :content
    = f.text_area :content, class: "pure-u-3-4"

  .pure-controls
    = f.submit "Create Conversation", class: "pure-button pure-button-primary"

app/views/conversations/show.html.slim
h1= @conversation.title
p.note= @conversation.note

ul.messages
  - @conversation.messages.each do |message|
    li
      .time.pure-u-2-24
        = message.sent_at.strftime '%H:%M:%S' if message.sent_at
      .channel.pure-u-2-24
        = message.channel.name if message.channel.present?
      .name.pure-u-3-24
        = message.participant.name
      .content.pure-u-17-24
        = message.content

app/views/layouts/application.html.slim
doctype html
html
  head
    title ChatArc
    = stylesheet_link_tag    'http://yui.yahooapis.com/pure/0.6.0/pure-min.css', media: 'all'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    #layout
      header
        .pure-menu
          = link_to 'ChatArc', root_path, class: 'pure-menu-heading'

      #content
        - flash.each do |name, message|
          div class=("flash-#{name}") = message

        = yield